
SRC_DIR="../src"

HEADER_FILE="geom_computation.hpp"
MODULE_NAME="geom_computation"

GEN_CODE_FOLDER="gen_code"
mkdir -p $GEN_CODE_FOLDER

HEADER_FILE_BASE="${HEADER_FILE%.*}"
HEADER_FILE_E="${HEADER_FILE_BASE}.e"
PYTHON_WRAPPER_FILE="py_$HEADER_FILE_BASE.c"
SETUP_FILE="$GEN_CODE_FOLDER/setup.py"

gcc -x c -E $SRC_DIR/$HEADER_FILE -o ${GEN_CODE_FOLDER}/$HEADER_FILE_E
ribosome python_wrapper.c.dna $MODULE_NAME $HEADER_FILE ${GEN_CODE_FOLDER}/$HEADER_FILE_E > ${GEN_CODE_FOLDER}/$PYTHON_WRAPPER_FILE

cp setup.py $GEN_CODE_FOLDER/setup.py 
cp $SRC_DIR/* $GEN_CODE_FOLDER/
